# Uncomment the next line to define a global platform for your project
# platform :ios, '8.0'


target 'YBAppleSignInDemo' do
  
  use_frameworks!

  pod 'YBAppleSignInSDK', :path => './YBAppleSignInDemo/'

  target 'YBAppleSignInDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'YBAppleSignInDemoUITests' do
    # Pods for testing
  end

end
