# Uncomment the next line to define a global platform for your project
# platform :ios, '8.0'


target 'YBAppleSignInDemo' do
  
  use_frameworks!

  pod 'YBAppleSignInSdk', :git =>  'git@github.com:zhencanbing/AppleSignInSdk.git', :tag => 'v0.0.5'

  target 'YBAppleSignInDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'YBAppleSignInDemoUITests' do
    # Pods for testing
  end

end
